### ISSUE TITLE
Successful upgrade except

### ISSUE THREAD

**Issue by StevensBrian** [Daniel-KM/Omeka-plugin-UpgradeToOmekaS#4]
Hi,

First, thanks for all the omeka related development that you do!

The administrative side of my recent omeka-s upgrade seems to function correctly, but the public facing site shows this error:
Omeka has encountered an error
Zend\ServiceManager\Exception\ServiceNotFoundException
A plugin by the name "identitycurrent_user" was not found in the plugin manager Zend\View\HelperPluginManager

You can see the public side at:
http://archives.library.wcsu.edu/drm/drm_s/s/danbury-railway-museum-digital-exhibits/page/homepage-site#content

**Well... Never mind**  

This was an issue of the theme not being assigned.  Once a theme was set, zend quit complaining.

Thanks,
Brian

**Comment by Daniel-KM** [comment]
Thanks for your note. The theme converter will be deprecated soon. In practice, it is generally quicker to rebuild the theme from scratch than to fix an upgraded one and it avoids to use the module UpgradeFromOmekaClassic. 
Here the issue is that the conversion from the Omeka classic function `current_user()` should be renamed `$this->identity()`.
